stages:
  clean:
    cmd: python src/clean.py
    deps:
    - data/raw/iris.csv
    - src/clean.py
    outs:
    - data/prepared/cleaned_iris.csv
  scale:
    cmd: python src/scale.py
    deps:
    - data/prepared/cleaned_iris.csv
    - src/scale.py
    outs:
    - data/prepared/prepared_iris.csv
  train:
    cmd: python src/train.py
    deps:
    - data/prepared/prepared_iris.csv
    - src/train.py

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/sklearn/train/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Train Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
- dvclive/plots/sklearn/test/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Test Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
